### ISSUE TITLE
Seems to work but...

### ISSUE THREAD

**Issue by Shubedobedo** [Khezen/docker-postgres#1]
Pg admin runs on 5050 but I cant connect to the database. If I use local pgadmin I can connect with no issues using the user:postgres and password:changeme

**Comment by khezen** [comment]
which version of Docker and docker-compose are you running? on which system?

**Comment by Shubedobedo** [comment]
Docker version 17.12.0-ce, build c97c6d6
docker-compose version 1.18.0, build 8dd22a96
I've tried on a windows system and Linux.

**Comment by khezen** [comment]
Which host do you try to connect to from pgadmin? is it `localhost` or `127.0.0.1`? How about you try `postgres`?

**Comment by khezen** [comment]
shall I close this issue?
