### ISSUE TITLE
Can not change postgres password

### ISSUE THREAD

**Issue by picbenoit** [Khezen/docker-postgres#13]
Hi,

First thank you so much for your work and for sharing it !

I'm new in Docker, so I need help for a problem.

All is working on my project except that I cannot change the postgres password.
It tried to changed it on my env file and next directly on the file, the password is ever "changeme".
Of course, I stop and restart docker after each change :
`docker-compose -f "docker-compose.yml" down`
`docker-compose -f "docker-compose.yml" up -d --build`

whereas the change of the identifiers of PGADMIN worked well. I changed it by adding values in my .env file.

Thanks,

Ben.

**Comment by picbenoit** [comment]
Is someone reproduce it ?

**Comment by H36615** [comment]
@picbenoit https://github.com/docker-library/postgres/issues/203#issuecomment-255200501

**Comment by TariqueNasrullah** [comment]
Did you try to remove the existing volumes?
`docker-compose -f "docker-compose.yml" down` doesn't remove the volumes.
