### ISSUE TITLE
About Data in PgAdmin4

### ISSUE THREAD

**Issue by ioricloud** [Khezen/docker-postgres#21]
Hey friend,

I am using your compose but I dont have persistence data in pgadmin, in database is ok, just only in pgadmin doesnt show for me.

Why?

**Comment by pablintino** [comment]
Hi, same problem here. It seems that the pgadmin volume has changed. I've changed the volume to be attached to /var/lib/pgadmin and it seems to work OK.
I can open a PR with the change if @khezen considers that it can be feasible.

**Comment by khezen** [comment]
Thanks @pablintino . I tested as well and checked current pgadmin documentation and `/var/lib/pgadmin` should fix this.
If you have the PR ready please submit. I'll merge it right away.

**Comment by pablintino** [comment]
Thanks for your fast response @khezen! I've submitted the PR as #22. Check it when you have time.

**Comment by khezen** [comment]
It's merged. Thanks guys.
