### ISSUE TITLE
postgres db is up  but pgadmin can't connect with error Connection Refused

### ISSUE THREAD

**Issue by curllog** [Khezen/docker-postgres#27]
Hi
i just used docker compose up -d 
when i want to add server i get below error

![image](https://user-images.githubusercontent.com/25693849/213888371-28ffb430-e827-4e75-be89-8b02008c41ab.png)**

can anybody help me ? thanks

**Comment by MyroslavBoiko** [comment]
1. Use postgres as hostname.  #https://github.com/khezen/compose-postgres/issues/6
2. Use internal Ipv4 of the pgAdmin container #https://stackoverflow.com/questions/53610385/docker-postgres-and-pgadmin-4-connection-refused

**Comment by curllog** [comment]
@MyroslavBoiko  Thanks
